document.write('<footer id="footer">');
document.write('    <div class="container">');
document.write('        <div class="row">');
document.write('          <div class="col-sm-12">');
document.write('                <div class="copyright-text text-center">');
document.write('                  <p><img src="images/logo.png" width="50px" alt="logo"></p>');
document.write('                    <p>LHC &copy;</p>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</footer>');
